### ISSUE TITLE
Add flexibility to the cells, clocks, and "Age" column used. 

### ISSUE THREAD

**Issue by CPRyan** [CPRyan/cellclockr#1]
Right now it uses only variables named "Age" and the Salas et al. 2022 12 immune cells. It also only includes PCHorvath1, PCPhenoAge, PCGrimAge, and DunedinPACE - I'd like to modify to use one as default, but to add additional capability for user to put in whichever cells or clocks they want.

**Comment by CPRyan** [comment]
We can use the ones that are there now as default input. But it would be nice if folks could use different versions of the cells and clocks if they want.

**Comment by will-marella** [comment]
Sorted
