### ISSUE TITLE
calculate_r2_w_age

### ISSUE THREAD

**Issue by CPRyan** [CPRyan/cellclockr#4]
If I include more than 1 variable in 'control_covariates' I get this error. 

Error in control_covariates != 1 && !all(control_covariates %in% colnames(data)) : 
  'length = 3' in coercion to 'logical(1)'

I checked and the variables are absolutely in the dataframe. 

![image](https://github.com/user-attachments/assets/74f24aca-e3b3-4585-a400-4b25147f0e7d)

**Comment by will-marella** [comment]
Fixed the erroneous error-checking in calculate_r2_w_age_helper.R. Thank you!
